language: java
sudo: false
jdk:
  - oraclejdk8
script:
  - mvn clean verify cobertura:cobertura
cache:
  directories:
  - .autoconf
  - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
